version=0.1
 [default.global.parameters]
 stack_name = "twitter-bot-stack"
 
 [default.deploy.parameters]
 stack_name = "twitter-bot-stack"
 s3_bucket = "twitter-bot-bucket"
 s3_prefix = "my-s3-prefix"
 region = "us-east-2"
 confirm_changeset = true
 capabilities = "CAPABILITY_IAM"
 tags = "project=\"twitter-bot\" stage=\"development\""
